# Generated by Django 5.2.4 on 2025-07-23 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('following_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('posts_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['followers_count'], name='users_profi_followe_929e8c_idx'), models.Index(fields=['following_count'], name='users_profi_followi_53f959_idx'), models.Index(fields=['posts_count'], name='users_profi_posts_c_ab933d_idx')],
            },
        ),
    ]
